export { HomePage } from "./HomePage";
export { AboutPage } from "./AboutPage";
export { ServicesPage } from "./ServicesPage";
export { ServiceDetailPage } from "./ServiceDetailPage";
export { ContactPage } from "./ContactPage";
export { PortfolioPage } from "./PortfolioPage";
export { BlogPage } from "./BlogPage";
export { BlogPostPage } from "./BlogPostPage";
export { NotFoundPage } from "./NotFoundPage";
